### ISSUE TITLE
Question about getAuthCode and access_token. (or maybe feature request?)

### ISSUE THREAD

**Issue by luiseok** [guruahn/vue-google-oauth2#10]
Hi. Thank you for sharing good code. 
This has helped me to improve my productivity.

During the development, I have questions about access_token. 
Is there any way to get `access_token` from the client side even if I log in with `getAuthCode()`?
[README.md](https://github.com/guruahn/vue-google-oauth2/blob/master/README.md) says that I can only access google user object through `signIn()` function. However, even if I authenticate on the server side with `getAuthCode()`, client can access to google user object by `window.gapi.auth2.getAuthInstance().currentUser.get().getAuthResponse()` ([GoogleUser.getAuthResponse](https://developers.google.com/identity/sign-in/web/reference#googleusergetauthresponseincludeauthorizationdata))
So, I would like to ask you how to access `access_token` or user profile in login via `getAuthCode()`.

If you have to access windows.gapi.auth2.getAuthInstance (as described above), it would be nice if you have an API that you can access directly from vue-google-auth2.

I'm sure you're busy, but I'd appreciate it if you could help me.

----
안녕하세요. 
먼저 좋은 라이브러리를 공유해주셔서 감사합니다. 덕분에 생산성 향상에 많은 도움이 되었습니다.

웹앱을 개발하던 중 access_token 관련한 궁금증이 생겨서 질문을 남깁니다. 
혹시 getAuthCode 함수를 통해 서버 사이드에서 로그인 했을 경우에도 클라이언트단에서 access_token을 획득 할 수 있는 방법이 있나요?
README.MD 에서는 signIn() 함수를 통해서만 google User 객체에 접근할 수 있다고는 하지만.. getAuthCode를 통해 서버사이드에서 인증하더라도 클라이언트에서는 `window.gapi.auth2.getAuthInstance().currentUser.get().getAuthResponse()` ([GoogleUser.getAuthResponse](https://developers.google.com/identity/sign-in/web/reference#googleusergetauthresponseincludeauthorizationdata)) 를 통해 액세스토큰에 접근할 수 있다고 알고있습니다.
그래서 혹시 getAuthCode를 통한 서버사이드 인증에서도 access_token이나 user profile에 접근하려면 어떻게 접근해야 하는지 질문드립니다.

만약 위에 기술했듯이 직접 window.gapi.auth2.getAuthInstance(이하생략) 를 호출해서 접근해야 한다면, vue-google-oauth2 에서도 직접 접근할 수 있는 API가 있다면 좋을것 같습니다.

바쁘시겠지만 도와주시면 감사하겠습니다.

**Comment by fidemin** [comment]
If you send auth_code from front-end to back-end server to get access_token (or refresh_token etc), there is no direct way to use access_token. You have to save tokens somewhere in backend such as database, and you have to request to get that tokens. Please refer to [here](https://camo.githubusercontent.com/72ddfc00510fe88794e7373694d25628aa419a65/687474703a2f2f692e696d6775722e636f6d2f425150584b79542e706e67).

If you use `signIn` method, you can access  [gapi.auth2.AuthResponse](https://developers.google.com/identity/sign-in/web/reference#gapiauth2authresponse) object by use the code `this.$gAuth.GoogleAuth.currentUser.get().getAuthResponse()`, everywhere.

**Comment by luiseok** [comment]
Thanks @yhmin for a quick response.
Even if authcode is acquired through `getAuthCode()` and authentication is processed on the server side, access_token is managed (can handle) by the Front Gapi library. You can access the token directly by entering `window.gapi.auth2.getAuthInstance().currentUser.get().getAuthResponse()` directly into the javascript console after logging in.
However, there was no way to access this library at the API level, so I left an issue.

**Comment by guruahn** [comment]
@luiseok 님 이슈남겨주셔서 감사합니다.
@yhmin84 님이 말씀하신대로 라이브러리의 `GoogleAuth` 메소드에 `window.gapi.auth2.getAuthInstance()` 를 할당해서 노출시키고 있습니다. 따라서 프론트 엔드에서도 로그인 된 상태라면  `this.$gAuth.GoogleAuth.currentUser.get().getAuthResponse()` 으로 `window.gapi.auth2.getAuthInstance().currentUser.get().getAuthResponse()`과 같은 결과를 얻을 수 있습니다.

**Comment by luiseok** [comment]
확인해보니 이상 없이 잘 가져와지네요.
감사합니다!
이슈는 닫도록 하겠습니다.

**Comment by guruahn** [comment]
감사합니다. 언제든지 이슈/풀리퀘스트 환영합니다.

**Comment by fidemin** [comment]
Short Translation for solution:
`this.$gAuth.GoogleAuth.currentUser.get().getAuthResponse()` is same as `window.gapi.auth2.getAuthInstance().currentUser.get().getAuthResponse()` for `gapi`. 

`this.$gAuth.GoogleAuth` is equivalent to `window.gapi.auth2.getAuthInstance()`

**Comment by guruahn** [comment]
In fact, the best answer is `GoogleUser.getAuthResponse()`

```
this.$gAuth.signIn()
      .then(GoogleUser => {
        //on success do something
        console.log('getAuthResponse', GoogleUser.getAuthResponse())
      })
      .catch(error  => {
        //on fail do something
      })
```

please read this [reference docs](https://developers.google.com/api-client-library/javascript/reference/referencedocs#googleusergetauthresponseincludeauthorizationdata)
