### ISSUE TITLE
$gAuth.isInit always return false

### ISSUE THREAD

**Issue by function1983** [guruahn/vue-google-oauth2#11]
main.js 
```
import GAuth from 'vue-google-oauth2'
const gauthOption = {
  clientId: 59xxxxxxxxxx-xxxxxxxxxxxxxxxxxxxx4u6k42sqsv49.apps.googleusercontent.com',
  scope: 'profile email',
  prompt: 'select_account'
}
Vue.use(GAuth,gauthOption)
```
View.vue
```
mounted() {
    let that = this;
    let checkGauthLoad = setInterval(function() {
      that.isInit = that.$gAuth.isInit;
      that.isSignIn = that.$gAuth.isAuthorized;
      if (that.isInit) clearInterval(checkGauthLoad);
    }, 5000);
  }
```
 __that.$gAuth.isInit is always false here__

I wonder if this is the library's expected behavior. I couldn't find the information in the README.MD but my guess is that my app needs the __oauth consent screen verified first__ by Google before I am able to use it. I am not so sure if it is the case here though.

What do you think the problem is?

**Comment by guruahn** [comment]
@function1983 thanks for your comment
It seems like the following cause
- low version : please check latest version(1.3.2)
- ~~The authentication process did not go through : When the `handleClickSignIn` function is called, the Authentication new tab appears. Did you see the `Google Authentication Tab`. sample capture below image~~  => sorry, actually `isInit` value set before `sign-in` process.
![sample capture](http://qpleple.com/img/post-how-to-make-people-login-into-your-website-with-their-google-account/google-login-2.png)

**Comment by function1983** [comment]
@guruahn thanks for the response.
- vue-google-oauth2 version is 1.3.2 through npm install
- Sadly, I see no Google Authentication Windows pop up
- I also tried another vue google auth and that library works as expected

**Comment by guruahn** [comment]
sorry, actually `isInit` value set before `sign-in` process.

well, `vue-google-oauth2` init process is as follows.

1. load `google api script` in your dom(head)
2. excute `window.gapi.auth2.init` 
3. `isInit`set `true`

The `google api script` may not be loaded. If the `google api script` not loaded, maybe you can see console error log. please show me the logs.
and, Tell us your browser/os version please.

**Comment by yhtanBAE** [comment]
@guruahn i had the exact same problem where isInit was awalys false. https://apis.google.com/js/api.js was loaded.

**Comment by ritiktaneja** [comment]
I am too facing the same issue. isInit always returns false if login attempt has been made earlier.
