### ISSUE TITLE
Types  declaration is missing

### ISSUE THREAD

**Issue by builder7777** [guruahn/vue-google-oauth2#12]
I have a typescript VueJS project. When adding this component, I'm getting `Could not find a declaration file for module 'vue-google-oauth2'` error. 
I've added the typedefs from [this repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gapi.client.oauth2) but that had no effect.

**Comment by hamzaarshad2** [comment]
Yes please I have the same issue.

**Comment by guruahn** [comment]
@builder7777 we updated [v1.3.4](https://github.com/guruahn/vue-google-oauth2/releases/tag/v1.3.4). check please 🙏🏽

**Comment by builder7777** [comment]
Just got around to trying it, and It threw a bunch of errors complaining about 'this' being type 'any' implicitly in the vue-google-oauth2 code.

**Comment by guruahn** [comment]
@builder7777 we updated v1.4.0. check please 🙏🏽
and
we made [sample project](https://github.com/guruahn/vue-google-oauth2-front-sample-type) for typescript.
I need your feedback.
thanks

**Comment by builder7777** [comment]
The updated package works great with TypeScript! Thank you!
