### ISSUE TITLE
Insight on multiple instances of this component throughout application

### ISSUE THREAD

**Issue by jensenkd** [guruahn/vue-google-oauth2#13]
I have multiple components that need to authenticate against different distinct apis with seperate scope and potentially seperate clientId.

How can I pull the implementation out of 'global' on main.js and set the gauthOptions locally in each component.

**Comment by jpfong** [comment]
Yep, me too. It is really something useful for an app I'm building. Unfortunately, plugins are built with only one config as parameters.

**Comment by guruahn** [comment]
@jensenkd thanks your comment.
Sorry, We will not provide an multiple instances with a distinguished scope or clientId. 🙏🏽
