### ISSUE TITLE
Scope to only 'email' is not effective in GAuth options?

### ISSUE THREAD

**Issue by romainr** [guruahn/vue-google-oauth2#14]
**Describe the bug**
scope to only 'email' is not effective. It always seem to be overridden and asking for more?

**To Reproduce**
1. Init with 
const gauthOption = {
  clientId: 'xxxxxx.apps.googleusercontent.com',
  scope: 'email',
  prompt: 'select_account'
}
Vue.use(GAuth, gauthOption)
2. Popup will display
3. Because the request sent has '&scope=openid%20profile%20email&'

**Expected behavior**
Ask only for the user email

**Desktop (please complete the following information):**
- Ubuntu
- Chrome

Wondering if it could be related to

Note: By default, the fetch_basic_profile parameter of gapi.auth2.init() is set to true, which will automatically add 'email profile openid' as scope.
https://developers.google.com/identity/sign-in/web/sign-in

**Comment by guruahn** [comment]
Thanks, @romainr 
Yes, you right!
If you hope scope only 'email', `fetch_basic_profile` must set to false.
````
const gauthOption = {
  clientId: 'xxxxxx.apps.googleusercontent.com',
  scope: 'email',
  prompt: 'select_account',
  fetch_basic_profile: false
}
Vue.use(GAuth, gauthOption)
````

**Comment by romainr** [comment]
Ha, I missed it! Thanks!

And in case: https://github.com/guruahn/vue-google-oauth2/pull/15
