### ISSUE TITLE
Promise on this.$gAuth.signIn() never resolved

### ISSUE THREAD

**Issue by TomTom101** [guruahn/vue-google-oauth2#16]
I am using the "Directly get back the access_token and id_token" in a Vue app, having the problem that the promise is never resolved. The account chooser opens, I select an account, after this no promise is resolved nor any other error to be found in the console.

This might not be related to your code since this a) has worked for me before and b) still is working on Safari!

```
this.$gAuth.signIn()
      .then(user => {
       // nor this, nor catch is being executed
       }).catch( (e) => {
          console.log("Auth error", e);
        });
```

I was hoping you have some suggestions of how to debug this and get to the source of it.

**Comment by guruahn** [comment]
@TomTom101 thanks your issue.
I want more information for debugging.
Please give me the following information
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Vue.js Version 
 - Console error log(text or screen shot) and your code snippet.

**Comment by TomTom101** [comment]
Thanks for replying!

The thing is, this seems to have little to do w/ OS or even Vue! There is no console output whatsoever because neither the then() nor the catch() is called. Also, the very same code works on a different computer w/ same OS and same browser! It always works on Safari.

I was hoping you have some experience w/ this issue or experienced yourself. I am out of ideas. If not please excuse me bugging you w/ this and thanks for the plugin!

Best,
t
Am 4. Juni 2019, 17:26 +0200 schrieb Jeongwoo Ahn <notifications@github.com>:

**Comment by TomTom101** [comment]
Oh dear. I've had this problem since months, first thing I checked then was Adblockers, and I thought this solved. Turns out, AdBlock was running again on that domain. Disabling it + creating new keys solved it

**Comment by guruahn** [comment]
Ok! Good! 😝
