### ISSUE TITLE
IE Compatibility issue

### ISSUE THREAD

**Issue by pvlreyes** [guruahn/vue-google-oauth2#17]
I received a syntax error without any details in Internet explorer for this module. Chrome and Firefox are working fine.

**Comment by guruahn** [comment]
hi! @pvlreyes
What is your IE browser version?

**Comment by pvlreyes** [comment]
Hi @guruahn ,
I currently have IE 11.

**Comment by guruahn** [comment]
ok, @pvlreyes 
Please check your babel configuration for es6.
You can see my sample vue.js project [vue-google-oauth2-front-sample.](https://github.com/guruahn/vue-google-oauth2-front-sample)
Welcome inquiries at any time.
Thanks.

**Comment by pvlreyes** [comment]
Thanks @guruahn . I tested your project and managed to load the page. But the login is not working properly even i am already logged in it is still says isSignIn: false. And when I click the sign in button the pop up appeared but nothing happens when I select my account.

**Comment by guruahn** [comment]
@pvlreyes 
1. Please make sure you are using your customer ID.
2. Make sure it is an approved IP or DOMAIN(at [google developer console](https://console.developers.google.com))
3. plz, give me Console error log(text or screen shot) and your code snippet.
