### ISSUE TITLE
Getting additional info while getAuthCode processing

### ISSUE THREAD

**Issue by ManoogD** [guruahn/vue-google-oauth2#2]
I'm using **(a) Handling Google sign-in, getting the one-time authorization code from Google** for getting code and then send it to backend. It works great but there is one feature/info more which I need when user make authentication. I need **mail address** which user choose and authenticated. So is it possible to know address while getting **authorizationCode** ? I hope it is possible because I don't want to use second approach: **(b) Alternatively, if you would like to directly get back the access_token and id_token**  only for getting address. Thanks!

**Comment by guruahn** [comment]
sorry, @ManoogD 
All my github notification had gone spam mail box. TT
were you fixed it?
you can get user info on back-end side.

**Comment by ManoogD** [comment]
@guruahn  Yes, I'm getting info on server side via token_id, thanks

**Comment by maestroDever** [comment]
@guruahn Hi
Please let me know how I can retrieve `id_token` either by getting AuthCode or SignIn
thnaks
