### ISSUE TITLE
Wont initalize 

### ISSUE THREAD

**Issue by JoeElectricImp** [guruahn/vue-google-oauth2#20]
Code taken from the sample keeps looping because the it never gets initialized 

I've added the localhost and correct port to the Authorized JavaScript origins and changed the client ID to be my own. It however keeps looping through this section of code

`  created() {
    let that = this;
    let checkGauthLoad = setInterval(function() {
      that.isInit = that.$gAuth.isInit;
      that.isSignIn = that.$gAuth.isAuthorized;
      if (that.isInit) clearInterval(checkGauthLoad);
    }, 1000);
  }`

**Comment by phaberest** [comment]
Make sure you did the required steps in the Google developer console

```
let checkGauthLoad = setInterval(() => {
  this.googleAuthReady = this.$gAuth.isInit
  if(this.googleAuthReady) clearInterval(checkGauthLoad)
}, 300);
```
This is the code I'm using in my `mounted()` and works

**Comment by JoeElectricImp** [comment]
Turned out to be a 3rd party cookies issue had to whitelist accounts.google in my chrome browser. Feel free to close this issue
