### ISSUE TITLE
How do I get this into Nuxt?

### ISSUE THREAD

**Issue by rlneub** [guruahn/vue-google-oauth2#25]
I tried it without nuxt and it does what I want but I cannot figure out how to make it work in Nuxt.

**Comment by guruahn** [comment]
I have never used nuxt. But I can explain it with reference to [this Guide](https://codesandbox.io/s/github/nuxt/nuxt.js/tree/dev/examples/plugins-vendor?from-embed).

1. install vue-google-oauth2
2. add plugin file.
/plugins/vue-google-oauth.js (The filename can be anything)
```
import Vue from 'vue'
import GAuth from 'vue-google-oauth2'
const gauthOption = {
  clientId: 'CLIENT_ID.apps.googleusercontent.com',
  scope: 'profile email',
  prompt: 'select_account'
}
Vue.use(GAuth, gauthOption)
```
3. configure nuxt
nuxt.config.js
```
export default {
  plugins: [
    { src: '~/plugins/vue-google-oauth.js', ssr: false }
  ]
}
```

**Comment by rlneub** [comment]
That is what I tried but the google signon screen would appear but none of the data was returned to my program. I am at a loss as to why.

**Comment by rlneub** [comment]
I added the plugin. I changed the client id. I called signout and the get get an undefined error for GoogleUser.

It works perfect without Nuxt but there is an issue in Nuxt I cannot find.

**Comment by guruahn** [comment]
sorry we cannot support nuxt. 
if you find solution, pull request please.
thanks.

**Comment by beng970804** [comment]
Should mention this package does not support Nuxt in the readme section

**Comment by guruahn** [comment]
@beng970804 yes, right.
i updated readme.
thanks

**Comment by guruahn** [comment]
we support nuxt now! https://github.com/guruahn/vue-google-oauth2/releases/tag/v1.5.3
