### ISSUE TITLE
Cannot sign out

### ISSUE THREAD

**Issue by rlneub** [guruahn/vue-google-oauth2#27]
I log in fine. 
I call signOut and then go to log in another user and I see I am logged in and can click on me and it does not even ask a password but puts me right in. This is a security breach.

I have looked and see there are 2 possible solutions, call the disconnect or call a revoke token.

**Comment by guruahn** [comment]
can i see your code snippet? 
and please tell me your os/browser  version. @rlneub

**Comment by rlneub** [comment]
Windows 10, Chrome

Loggin in -- this works and I get profile info names

   this.$gAuth
      .signIn()
      .then((GoogleUser) => {
        // on success do something
        console.log('GoogleUser', GoogleUser)
        console.log('getId', GoogleUser.getId())
        console.log('getBasicProfile', GoogleUser.getBasicProfile())
        console.log('getAuthResponse', GoogleUser.getAuthResponse())
        console.log('getname', GoogleUser.getBasicProfile().getName())
        console.log('getEmail', GoogleUser.getBasicProfile().getEmail())
        console.log('getLast', GoogleUser.getBasicProfile().getFamilyName())

        this.isSignIn = this.$gAuth.isAuthorized
        console.log('isSignIn', this.isSignIn)

        const data = {
          loggedin: this.isSignIn,
          user: GoogleUser.getBasicProfile().getName(),
          email: GoogleUser.getBasicProfile().getEmail(),
          token: 'https://accounts.google.com/o/oauth2/revoke?token={' + GoogleUser.getId() + '}'
        }

        this.$bus.$emit('LogOn', data)
      })
      .catch(() => {
        // on fail do something
        const isloggedin = this.$gAuth.isAuthorized
        console.log('Fail ', isloggedin)
        this.$router.push({ path: '/' })
      })


1st log out code

   handleClickSignOut() {
      this.$gAuth
        .signOut()
        .then(() => {
          //on success do something
          this.isSignIn = this.$gAuth.isAuthorized;
        })
        .catch(error => {
          //on fail do something
                                console.log('Fail', error)
        })
               }


No fail. But when another user goes to log in it brings up the old user and the states is not logged off

2nd attempt

    async logoffClicked () {
      const token = await this.$gAuth.getAuthCode()
      console.log('token=' + token + ' this.token=' + this.token)
      this.$gAuth.GoogleAuth.disconnect()
      this.loggedin = false
      this.user = ''
      this.$router.push({ path: '/' })
    },

Still not logged off

**Comment by guruahn** [comment]
please write `console.log('isSignIn', this.$gAuth.isAuthorized);` like followe code.
```
handleClickSignOut() {
  this.$gAuth
    .signOut()
    .then(() => {
      //on success do something
      this.isSignIn = this.$gAuth.isAuthorized;
      console.log('isSignIn', this.$gAuth.isAuthorized);
    })
    .catch(error => {
      //on fail do something
      console.log('Fail', error)
    })
}
```
when you excute `handleClickSignOut()`, can you see log like this`isSignIn false` ?

**Comment by rlneub** [comment]
this.isSignIn = false

Go to log in again and still not signed out
I an the top user in the photo
![signin](https://user-images.githubusercontent.com/3831992/70160448-81f67f00-1688-11ea-8d5f-a1eb092ac08c.png)

**Comment by rlneub** [comment]
this.isSignIn = false

Go to log in again and still not signed out
I an the top user in the photo
![signin](https://user-images.githubusercontent.com/3831992/70160448-81f67f00-1688-11ea-8d5f-a1eb092ac08c.png)

**Comment by guruahn** [comment]
that is not error. google is continue your login session until you log out manualy in google.
![image](https://blogfiles.pstatic.net/MjAxOTEyMDVfNDAg/MDAxNTc1NTEwNzUyNzMw.pCBibOyuAjhKXBDlsQU7wzIFhzvF4T4mfjeIBNPiDKsg.OgFyg-1DcJFfX5cxJe0meTAE9TZ9LkVJhNmGgJO10W0g.PNG.anmarine/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7_2019-12-05_%EC%98%A4%EC%A0%84_10.37.51.png)

thanks

**Comment by rlneub** [comment]
So, if I have a receptionist log in after an admin logs out she can select the admin and automatically logged in and function as an admin?

By not revoking the login, people can select other loogin in users and use their credentials.

There has to be a way programatically to log out a user from an application without having to leave the application and go to the browser to log out.

**Comment by guruahn** [comment]
@rlneub 
Maybe it makes no sense to force logout of service b in service a.
Google api just support your login system. 
but, Maybe the code below will help you.(You may have seen it.)
```
document.location.href = "https://www.google.com/accounts/Logout?continue=https://appengine.google.com/_ah/logout?continue=http://localhost:4200";
```
change `http://localhost:4200` to your redirect url.
