### ISSUE TITLE
How to use: getting email address?

### ISSUE THREAD

**Issue by gregfr** [guruahn/vue-google-oauth2#29]
Greetings and thank you for this project.

I was able to set it up, but I don't know how to actually use it: my backend server gets a token, what can I do with it? how can I fetch information, such as email, from it?

Thanks in advance

**Comment by gregfr** [comment]
I realized this was not part of this package, but done with Google SDK. There is a tutorial here: https://skarlso.github.io/2016/06/12/google-signin-with-go/

Basically, after you get the token, you do something like that:

```
		client := conf.Client(ctx, token)

		if resp, err := client.Get("https://www.googleapis.com/oauth2/v3/userinfo"); err != nil {
			logger.WithError(err).Error("cannot fetch user info from Google")
			return nil
		} else {
			defer resp.Body.Close()
			data, err := ioutil.ReadAll(resp.Body)
			if err != nil {
				logger.WithError(err).Error("cannot read user info from Google")
				return nil
			}
			logger.Infof("User info: %s", string(data))

		}
```

Hope it helps

**Comment by fidemin** [comment]
There are many APIs in google which can be called using personal access_token and api key. This is not directly related to our package! Thanks!
