### ISSUE TITLE
Unhandled promise rejection TypeError: "window.gapi.auth2 is undefined"

### ISSUE THREAD

**Issue by xnaveira** [guruahn/vue-google-oauth2#3]
Getting this when using it with vuejs 2.0, haven't been able to find the root cause. Maybe something with the js api client injection?

**Comment by maxchou415** [comment]
same problem

**Comment by guruahn** [comment]
@xnaveira @maxchou415 
sorry, I missed 'gapi.load' 
please update to 1.0.10
