### ISSUE TITLE
Edge Error: CustomError: Error in protected function: The window does not have an opener!

### ISSUE THREAD

**Issue by davideversonmdh** [guruahn/vue-google-oauth2#33]
**Describe the bug**
Using this component to authenticate via Google.  Works in Chrome, FireFox. Having issues with Edge. 

With Edge, in the application click on Login.  A separate window opens allowing me to either select my account or to provide credentials.  After this, the window just says "One moment please...".  In the console this error is outputted "CustomError: Error in protected function: The window does not have an opener!"  There are no console messages in the original window (where the application is).  This never goes away. 

The correct URLs are setup in Google. 

An odd behavior is that when testing on localhost (no https), the login works fine.  This is happening in our integrated test environment where we do have https. 

**To Reproduce**
See above.

**Expected behavior**
The google authentication window should be dismissed and proceed with the application flow.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version Microsoft Edge 42.17134.1098.0

**Additional context**
Component version 1.5.3
Vue 2.6.11

**Comment by guruahn** [comment]
@davideversonmdh Thank you for the issue. I'll check it.

**Comment by guruahn** [comment]
@davideversonmdh 
I didn't find the problem on my windows Edge. can you try here [Front-end Demo](https://stupefied-darwin-da9533.netlify.app/).
and, I cannot debug in google account window. 

- please check vue-google-oauth2 version. latest version is [1.5.4](https://github.com/guruahn/vue-google-oauth2/releases)
- or check Edge settings.

This is the only advice I can give.

**Comment by guruahn** [comment]
I haven't solved it yet
This is a very old issue, so I will close it.
