### ISSUE TITLE
error in parent page "popup_closed_by_user"

### ISSUE THREAD

**Issue by guruahn** [guruahn/vue-google-oauth2#34]
**Describe the bug**
shown error, when the google sign-in popup  closed

**To Reproduce**
1. Go to [Front-end Demo](https://stupefied-darwin-da9533.netlify.app/)
2. test sign-in
3. google sign-in popup open, and complete google login, and popup close.
4. See error in parent page
error: "popup_closed_by_user" (cb=gapi.loaded_0 (268,25))

**Desktop (please complete the following information):**
 - OS: Window
 - Browser Edge
 
**Not always, but sometimes this happens.**

**Comment by Wickeey** [comment]
maybe there are better solutions but this worked for me

```
methods: {
    async googleSignIn() {
      const googleUser = await this.$gAuth.signIn().catch(() => {
        return null
      })

      if (!googleUser) {
        return null
      }
      .....
    }
}
```

**Comment by guruahn** [comment]
@Wickeey Thank you. It seems to be resolved.
