### ISSUE TITLE
Error sign in on instagram viewer

### ISSUE THREAD

**Issue by roxigonzalez** [guruahn/vue-google-oauth2#35]
I'm not able to sign in on Instagram viewer. FB viewer and another apps allow but Instagram doesn't.

**Comment by roxigonzalez** [comment]
Even front demo https://stupefied-darwin-da9533.netlify.app/ doesn't work.

**Comment by guruahn** [comment]
@roxigonzalez Thank you for the issue. I'll check it.

**Comment by guruahn** [comment]
I haven't solved it yet
This is a very old issue, so I will close it.
