### ISSUE TITLE
Why after login the website keep sending XHR?

### ISSUE THREAD

**Issue by elior99** [guruahn/vue-google-oauth2#36]
Hey,
After using handleClickGetAuth(), on every refresh i see XHR request to:
"https://accounts.google.com/o/oauth2/iframerpc?action=issueToken..."
And
"https://accounts.google.com/o/oauth2/iframerpc?action=checkOrigin&origin=..."

I don't understand why it keeps sending on each refresh although i didn't set anything to run on load/created.
Only the function "handleClickGetAuth()" which trigger onclick

**Comment by guruahn** [comment]
Hi @elior99 
Please let me know your app's execution environment.(e.g. macOS/Chrome)
And I wish you could give me some of your Vue.js code too.
The sample project does not show such a problem.

**Comment by elior99** [comment]
I'm using windows, chrome and webpack.
the code: 
```
handleClickGetAuth(){
         
      this.$gAuth.getAuthCode()
    .then(authCode => {
        // On success
       
        console.log(authCode)
        return this.$http.post('http://localhost:8080/app.php?test=1', { code: authCode, redirect_uri: 'postmessage' })
      })
      .then(response => {
        // And then
        console.log(response)
       
      })
      .catch(error => {
        // On fail do something
         console.log(error)
      })
    },
```

Which triggered by button.
The issue is that, onload the XHR is sending without clicking the button..
When i comment "Vue.use(GAuth, gauthOption)" it's doesn't make the XHR..

**Comment by guruahn** [comment]
@elior99  `Google OAuth` stores some information(white list, etc) in browser local storage. If this information is expired or deleted, get the information through 'https: //accounts.google.com/o/oauth2/iframerpc? Action = che ...' and check your domain and save it to the local storage again. So, I think you should doubt the following two things.
- Are you forcibly emptying the local storage?
- Or is it not set to use local storage?

**Comment by elior99** [comment]
I'm not emptying the local storage, i'm actually can see information stored form account.google.com in my localstorage..
Maybe it's related to the fact i'm in localhost?

**Comment by guruahn** [comment]
@elior99 
Even if it is a localhost, it is no problem if it is registered on [API Console](https://support.google.com/googleapi/answer/6158849?hl=en&ref_topic=7013279#authorized-domains).
Are there any console errors?

**Comment by guruahn** [comment]
@elior99 
Perhaps the situation is not an error. I don't know why, but I could see the same phenomenon in my project **using getAuthCode**.
