### ISSUE TITLE
Tip for handling the auth code in python backend

### ISSUE THREAD

**Issue by manangouhari** [guruahn/vue-google-oauth2#37]
Hi, the library works perfectly and gets the auth code on the frontend.
Now I made a POST route in flask(python web framework) which uses the exact code from the Python backend sample provided in this repo. 
For some reason, I get this error - `invalid_grantMalformed auth code.`
I've been scratching my head over this for a while now. 
Can somebody please shed some light on what could be the potential reasons for this error.

**Comment by guruahn** [comment]
hi! @manan2002 
Please refer to [this article](https://blog.timekit.io/google-oauth-invalid-grant-nightmare-and-how-to-fix-it-9f4efaf1da35).
I hope this article helps you.
