### ISSUE TITLE
Keeps opening "Sign In With" and "Allow Access" windows every time

### ISSUE THREAD

**Issue by humoyun** [guruahn/vue-google-oauth2#4]
Whenever I try to sign in with google-sign-in button which will call 
`const gAuthCode = await this.$gAuth.getAuthCode();`
It is opening popup windows, abovementioned, every time!

**Comment by SuPenguin** [comment]
I've made a pull request for this https://github.com/guruahn/vue-google-oauth2/pull/5 to remove the Allow Access part.

**Comment by guruahn** [comment]
I'm merged #5  pull request by @SuPenguin. thanks @SuPenguin.
But i think @Humoyun 's issue is different problem.

@Humoyun, thanks your issue. "Sign in with" window is open still whenever you try to get authCode. You do not need to try to get authCode every time. 
authCode is one-time code. Server use the authCode to get accessToken or refreshToken. Server can get user information with that token.  So you do not need authCode anymore until the token expires. You must disable the sign-in button until the token expires.
It has been described in [Google sign-in flow works](https://github.com/guruahn/vue-google-oauth2#additional-help).
