### ISSUE TITLE
getAuthResponse() never returns a refresh_token

### ISSUE THREAD

**Issue by GrahamHouse** [guruahn/vue-google-oauth2#45]
Hi,

The function getAuthResponse() never returns a refresh_token.

I've added prompt: 'consent' to the config and I've removed the previously approved application from my Google account (because apparently the refresh_token is only issued on the first approval).

My code is as follows

```
import GAuth from 'vue-google-oauth2';
const configGAuth = {
    clientId: [CLIENT_ID],
    scope: 'https://www.googleapis.com/auth/drive.readonly',
    prompt: 'consent'
}
Vue.use(GAuth, configGAuth);
```

Then:

```
this.$gAuth.signIn()
.then(GoogleUser => {
    var authResult = GoogleUser.getAuthResponse();
})
```

This always returns:

```
access_token: "xxx"
expires_at: 1599153341490
expires_in: 3599
first_issued_at: 1599149742490
id_token: "xxx"
idpId: "google"
login_hint: "xxx"
scope: "email profile openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/drive.readonly"
```

I've even tried this on a brand new Google account and still the same.  Is there a configuration option not in the docs?  According to Google there's an 'access_type' option that needs to be 'offline' in order to be issued a refresh token but I don't see reference to this in the docs.

**Comment by guruahn** [comment]
Refresh tokens cannot be obtained directly from the browser. [If you get the authCode and pass it to the server side, you can get the refresh token on the server side.](https://github.com/guruahn/vue-google-oauth2#getting-authorization-code)
See the backend sample code [here](https://github.com/guruahn/vue-google-oauth2#sample-code).

**Comment by jahangirkabir** [comment]
I have already set prompt: 'consent'. but still no refresh token.
How to refresh token in the backend?

**Comment by guruahn** [comment]
Sorry, but I can't answer backend issues.
