### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by caobaloc12** [guruahn/vue-google-oauth2#46]
**Describe the bug**
SyntaxError: Unexpected token 'export' after nuxt app compiled

**To Reproduce**
1. Install package and create a plugin: 'vue-google-oauth2.js'
2. Include the plugin in nuxt.config.js
3. Wait for nuxt app compile successfully
4. Access nuxt app on browser

**Expected behavior**
Nuxt app running without error

**Screenshots**
![image](https://user-images.githubusercontent.com/9375011/94645894-30099e80-0317-11eb-9096-8e4dbf7b8448.png)

**Desktop
 - OS: Mac OS
 - Browser: Chrome
 - Version: 85.0.4183.121

**Comment by brightchip** [comment]
DId you figure out
Edit: You just need move the plugin into client only

**Comment by skysxu** [comment]
> DId you figure out
> Edit: You just need move the plugin into client only

this help me to solve the problem i had like the OP
