### ISSUE TITLE
vue-google-oauth2 on Vue3

### ISSUE THREAD

**Issue by talgolan** [guruahn/vue-google-oauth2#47]
Does anyone have an example of how to make vue-google-oauth2 work properly with Vue3 + Vuex + VueRouter?

**Comment by insomniac807** [comment]
following

**Comment by boussadjra** [comment]
@insomniac807 you could also watch the releases probably they would release a new version that supports vue 3.

**Comment by guruahn** [comment]
I started [new project](https://github.com/guruahn/vue3-google-oauth2) for vue3. 😎
@talgolan @insomniac807
