### ISSUE TITLE
 how to get token.pickle by authorization_response or auth_code

### ISSUE THREAD

**Issue by jahangirkabir** [guruahn/vue-google-oauth2#50]
`flow.fetch_token(authorization_response=authorization_response)`
`credentials = flow.credentials`

I am using Django in backend and VUE in frontend, wanted to use [this](https://developers.google.com/identity/protocols/oauth2/web-server#exchange-authorization-code) way.

I have also tried to get the token.pickle with auth_code
`flow.fetch_token(code=auth_code)`
This also didn't work.

I want to use token.pickle for multiple time like [this](https://developers.google.com/calendar/quickstart/python). is there any way to get that?

**Comment by guruahn** [comment]
Sorry, but I can't answer backend issues.
