### ISSUE TITLE
Can I only get authCode with out access token

### ISSUE THREAD

**Issue by t-tien** [guruahn/vue-google-oauth2#53]
When i use `this.$gAuth.getAuthCode()` function, I can get `authCode` but if I open network tab I can see also `access_token` and more info, I'm only want to get `authCode` without `access_token`, can I do this? Thank you!
<img width="320" alt="Screen Shot 2020-12-14 at 10 35 54" src="https://user-images.githubusercontent.com/30063599/102031114-4bedee00-3df8-11eb-9086-4b5123a19522.png">

**Comment by guruahn** [comment]
sorry but I don't know about that.

**Comment by Kapil-chn7** [comment]
How can i exchange code  from the server, if my client side is running on port 8080 and server is running 5000?
I tried to do this but i got an error, reporting redirect uri mismatch.
Thanks in advance

**Comment by guruahn** [comment]
This plugin does not support the new Google authentication system(GIS).
You need to migrate by referring to [this document](https://developers.google.com/identity/oauth2/web/guides/migration-to-gis?hl=en).
I'm sorry to tell you this news.
