### ISSUE TITLE
Although of set fetch_basic_profile to false, email profile openid are automatically added as scope.

### ISSUE THREAD

**Issue by t-tien** [guruahn/vue-google-oauth2#54]
**Describe the bug**
I'm using this library to get authCode from Google OAuth server, I set scope to `adwords` and `fetch_basic_profile` to false but when i see response from server, `email profile openid` are automatically added as scope.
My gAuthOptions: 

```
gauthOption = {
    clientId: process.env.VUE_APP_GOOGLE_CLIENT_ID,
    fetch_basic_profile: false,
    prompt: "consent",
    access_type: "offline",
    scope: "https://www.googleapis.com/auth/adwords"
  };
```

**Expected behavior**
Server only response for `adwords` scope without `email profile openid`

**Comment by guruahn** [comment]
thanks your issue. 👍
I will deal with it soon. 🚀

**Comment by guruahn** [comment]
I'm curious if you could actually access all of that data(email, profile, openid).

**Comment by ynechaev** [comment]
@guruahn https://github.com/guruahn/vue-google-oauth2/blob/3d43ee5d21b0d29a99052b355e86d4208be5a1c3/index.js#L132

**Comment by guruahn** [comment]
@ynechaev 
There is also code like this:
    if (options.scope) GoogleAuthConfig.scope = options.scope
Line 136

**Comment by guruahn** [comment]
What I want to say is, can you actually get the user's email, profile and openid information from the response results?
In fact, if you don't get real email, profile and openid values, there is no problem.
