### ISSUE TITLE
isInit never set to true due to idpiframe_initialization_failed error

### ISSUE THREAD

**Issue by glibt** [guruahn/vue-google-oauth2#55]
$gAuth.isInit property is never set to true due to the following error being thrown by the module.

**details: "Cookies are not enabled in current environment."
error: "idpiframe_initialization_failed"**

![image](https://user-images.githubusercontent.com/2303234/104769576-5c112a00-5724-11eb-9255-08adafa86463.png)

Chrome then also displays the cookies blocked icon in the URL bar.

My configuration is as follows:

![image](https://user-images.githubusercontent.com/2303234/104769644-7a772580-5724-11eb-83e4-5c509d57598d.png)

Any idea what could be causing this & how to resolve this?

**Comment by mediv0** [comment]
you are probably blocking cookies in your env
unchecking ` block third party cookies ` under Cookies options in google chrome ( if you're using it ofc!) will solve this problem

**Comment by glibt** [comment]
@mediv0 @guruahn Is there not a way to implement google auth without 3rd party cookies?

**Comment by guruahn** [comment]
@glibt 
Please refer to [this article](https://developers.google.com/identity/sign-in/web/troubleshooting#third-party_cookies_and_data_blocked).
