### ISSUE TITLE
Expected 1 argument, but got 0 in index.ts

### ISSUE THREAD

**Issue by xorbis** [guruahn/vue-google-oauth2#58]
**Describe the bug**
Typescript vue-cli compiler returns this error.

`ERROR in node_modules/vue-google-oauth2/index.ts(17,13):
17:13 Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?
    15 |         if (!script.readyState || /loaded|complete/.test(script.readyState)) {
    16 |           setTimeout(() => {
  > 17 |             resolve();
       |             ^
    18 |           }, 500);
    19 |         }
    20 |       };`

**To Reproduce**
1. Update all npms using ncu -u
2. Execute the serve command in vue-cli

**Expected behavior**
Expect vue-google-oauth2 to transpile properly.

**Comment by guruahn** [comment]
Sorry,
Please exclude this plugin from the tslint.
It is difficult to support TypeScript anymore.
