### ISSUE TITLE
refresh token

### ISSUE THREAD

**Issue by talha118** [guruahn/vue-google-oauth2#6]
Hey,

Is there anyway to get refresh token?

Thanks

**Comment by guruahn** [comment]
Hi, @talha118 
you can get refresh token on back-end side only.
first, Use the `this.$gAuth.getAuthCode()` on the front-end to get the `authCode`.
then, Send `authCode` to back-end side.
finally, you can get `refresh token` on back-end side.
You can see the sample back-end code in [this article](https://developers.google.com/identity/protocols/OAuth2WebServer#exchange-authorization-code).
