### ISSUE TITLE
Can't manage multiple instances

### ISSUE THREAD

**Issue by philchass** [guruahn/vue-google-oauth2#60]
The package can't manage multiples instances of authorization => rights in the same app.

It could be nice to name the variable this.$gauth to manage multiples rights (scopes) when we ask for this.$gAuth.getAuthCode()

**Comment by chenlevy** [comment]
That will be very useful for me also

**Comment by adamposledni** [comment]
@philchass  @chenlevy 

**Solution**
I needed something similiar for my app. I have made few changes so the plugin supports multiple scopes.

[Forked and updated code here](https://github.com/hroudaadam/vue-google-oauth2/blob/exp/multiple-scopes/index.js)

**How to use it with Vue.js app**

*in main.js*
```javascript
const gauthOption = {
  clientId: 'xxx', // only client id is neede -> you don't set prompt and scopes globally anymore
};

Vue.use(GAuth, gauthOption);
```

*in your components*
```javascript
const googleUser = await this.$gAuth.signIn({
    prompt: "select_account", 
    scope: "profile email", // you can now specify scopes for every gAuth method call
});
const authResponse = googleUser.getAuthResponse();
```

**Comment by guruahn** [comment]
This plugin does not support the new Google authentication system(GIS).
You need to migrate by referring to [this document](https://developers.google.com/identity/oauth2/web/guides/migration-to-gis?hl=en).
I'm sorry to tell you this news.
