### ISSUE TITLE
How to make it so this work properly with Typescript?

### ISSUE THREAD

**Issue by alexdpoon** [guruahn/vue-google-oauth2#65]
I got rid of TS lint errors by doing this:

```
import GAuth from 'vue-google-oauth2'
import Vue from 'vue'
declare module 'vue/types/vue' {
  interface Vue {
    $gAuth: any
  }
}
```

But specifying it as **any** doesn't really enforce types. Can someone help me figure out to make $gAuth the correct type?

**Comment by skrzypczynskiM** [comment]
Did you figure it out?

**Comment by abhijeetj100** [comment]
Hi, Just started using this Plugin, curious to know if there is any development related to proper types for $gauth?

**Comment by guruahn** [comment]
This plugin does not support the new Google authentication system(GIS).
You need to migrate by referring to [this document](https://developers.google.com/identity/oauth2/web/guides/migration-to-gis?hl=en).
I'm sorry to tell you this news.
