### ISSUE TITLE
How can i exchange code  from the server, if my client side is running on port 8080 and server is running 5000?

### ISSUE THREAD

**Issue by Kapil-chn7** [guruahn/vue-google-oauth2#66]
How can i exchange code  from the server, if my client side is running on port 8080 and server is running 5000?
I tried to do this but i got an error, reporting redirect uri mismatch.
Thanks in advance

_Originally posted by @Kapil-chn7 in https://github.com/guruahn/vue-google-oauth2/issues/53#issuecomment-850949909_

**Comment by guruahn** [comment]
This plugin does not support the new Google authentication system(GIS).
You need to migrate by referring to [this document](https://developers.google.com/identity/oauth2/web/guides/migration-to-gis?hl=en).
I'm sorry to tell you this news.
