### ISSUE TITLE
Please add error from google to the API.

### ISSUE THREAD

**Issue by thomaspsik** [guruahn/vue-google-oauth2#67]
**Describe the bug**
During initialisation the error from google is checked and displayed on the console.

**To Reproduce**
Use a URL for your website that is not registered at google.

**Expected behavior**
Get the error from Google through the API for further usage.

**Proposal**
after Line 58:
          console.error(error)
add 
          this.goggle_error = error

So that the error can be displayed in the website (if you wish so). 

Thank you for considering the request.

**Comment by guruahn** [comment]
This plugin does not support the new Google authentication system(GIS).
You need to migrate by referring to [this document](https://developers.google.com/identity/oauth2/web/guides/migration-to-gis?hl=en).
I'm sorry to tell you this news.
