### ISSUE TITLE
Can't login in facebook mobile browser

### ISSUE THREAD

**Issue by ocajda2** [guruahn/vue-google-oauth2#68]
**Describe the bug**
Can't login by google if I open link to my website in facebook mobile app. In other browsers it is working correctly. 

**To Reproduce**
1. Click on Login by Google button
2. Choose your account
3. Waiting screen with loading circle is visible and won't disappear 

My code:
` const user = await this.$gAuth.signIn()`
       ` let token = ''`
        `const authResponse = user.getAuthResponse()`
        `if (authResponse) {`
          `   token = authResponse.access_token`
        `}`
`this.$store.dispatch('loginGoogle', token)`

Thanks for advice.

**Comment by NgallaJuke** [comment]
`this.$gAuth.signIn()`
is working fine on desktop but the popup is not is not showing on mobile. Actually it does for my phone but I tried on two other but they don't

**Comment by guruahn** [comment]
This plugin does not support the new Google authentication system(GIS).
You need to migrate by referring to [this document](https://developers.google.com/identity/oauth2/web/guides/migration-to-gis?hl=en).
I'm sorry to tell you this news.
