### ISSUE TITLE
Adding `ux_mode: 'redirect'` does not work

### ISSUE THREAD

**Issue by adbeel92** [guruahn/vue-google-oauth2#69]
The login dialog opens a popup and if you add `ux_mode: 'redirect'` should not open it, but it's opening it

**Comment by smonff** [comment]
I was dealing with the same issue and found your ticket. What did you try? Those are the options I passed to `vue-google-oauth2`:

```
{
  clientId: 'secret',
  prompt: "select_account",
  redirect_uri: encodeURI('http://localhost:8080/'),
  scope: "profile email",
  ux_mode: "redirect",
}
```

See that you'll need a `redirect_uri` parameter in addition to `ux_mode`. Also, totally log-out from Google and hard refresh (even restart?) the browser and flush cookies for Google Identity might help.

With this configuration, the popup is not used.

**Comment by guruahn** [comment]
This plugin does not support the new Google authentication system(GIS).
You need to migrate by referring to [this document](https://developers.google.com/identity/oauth2/web/guides/migration-to-gis?hl=en).
I'm sorry to tell you this news.
