### ISSUE TITLE
isInit is not reactive nor a promise/callback

### ISSUE THREAD

**Issue by igalgh** [guruahn/vue-google-oauth2#70]
Using setInterval to poll `isInit` is not performant and goes against best practices. 
Since it's not reactive, it's not possible to rely on it's value in vue computed properties.

I suggest to make isInit a promise. 

This can be achieved by assigning it the non-caught promise returned by `installClient()` on line 50:
```js
this.load = (config: any, prompt: string) => {
      this.isInit = installClient()
        .then(() => {
          return initClient(config);
        })
        .then((gapi: any) => {
          this.GoogleAuth = gapi.auth2.getAuthInstance();
          this.prompt = prompt;
          this.isAuthorized = this.GoogleAuth.isSignedIn.get();
        })
      this.isInit.catch((error) => {
        console.error(error);
      });
    };
```
Such a change allows `this.$gauth.isInit.then(...).catch(...)` instead of the setinterval

Note: 
- This requires a major version upgrade as it breaks compatibility
- If a minor version upgrade is preferred, it's possible to add to the API a new `this.isInitPromise` member which gets initialized in the proposed way

**Comment by guruahn** [comment]
This plugin does not support the new Google authentication system(GIS).
You need to migrate by referring to [this document](https://developers.google.com/identity/oauth2/web/guides/migration-to-gis?hl=en).
I'm sorry to tell you this news.
