### ISSUE TITLE
Google Sign-In JavaScript Platform Library will be discontinued 

### ISSUE THREAD

**Issue by pauladiniz** [guruahn/vue-google-oauth2#73]
Google is discontinuing the Google Sign-In JavaScript Platform:
https://developers.google.com/identity/sign-in/web/sign-in

From now on, we'll need the Google Identity Services SDK.

Should I just remove vue-google-oauth or it's safe to keep it in my project?

**Comment by hasanmuzak** [comment]
Any update? It throws a warning such as;

 "Your client application uses libraries for user authentication or authorization that will soon be deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information."

**Comment by guruahn** [comment]
#78 same issue
