### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '$gAuth')

### ISSUE THREAD

**Issue by Maru-Yasa** [guruahn/vue-google-oauth2#76]
i got this error when try to using signIn() method, and excute the login function in btn `@click="login()"`

```  methods : {
        login: async () => {
            const test = await this.$gAuth.signIn()
            console.log(test);
        },
    }
```
initialization in main.js
```
import Vue from 'vue'
const gauthOption = {
  clientId: blablablaba
  scope: 'profile email',
  prompt: 'select_account'
}

Vue.use(GAuth, gauthOption)
```

any solution for this problem or i just missed up somethings?

**Comment by guruahn** [comment]
The fact that 'this' is in an undefined state doesn't seem to be caused by this plugin.
