### ISSUE TITLE
cb=gapi.loaded_0?le=scs:260 Your client application uses libraries for user authentication or authorization that will soon be deprecated

### ISSUE THREAD

**Issue by Gregory-Han** [guruahn/vue-google-oauth2#77]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abdelkarimAzzouguagh** [comment]
I'm having the same problem, any solution?

**Comment by guruahn** [comment]
#78 same issue
